import com.example.html.html
import cz.scorpionsoft.kotlin.demos.Person

class Button(private val onClick: () -> Unit) {
    fun performClick() {
        onClick()
    }
}

class ButtonClickListener(private val name: String) {
    fun onClick() {
        println(name)
    }
}

class ScreenView {
    var listener = ButtonClickListener("First")
    val buttonLambda = Button { listener.onClick() }
    val buttonReference = Button(listener::onClick)
}

class IntTransformer : (Int) -> Int {
    override fun invoke(p1: Int): Int {
        TODO("Not yet implemented")
    }
}


fun main(args: Array<String>) {

    val res = html {
        head {
            title { +"Muj titulek" }
        }

        body {
            h1 { +"XML encoding with Kotlin" }
            p { +"this format can be used as an alternative markup to XML" }

            a(href = "www.idnes.cz") { +"Kotlin" }

            // mixed content
            p {
                +"This is some"
                b { +"mixed" }
                +"text. For more see the"
                a(href = "http://kotlinlang.org") { +"Kotlin" }
                +"project"
            }
            p { +"some text" }

            // content generated by
            p {
                for (arg in args)
                    +arg
            }
        }
    }

    println(res.toString())

}

fun main2(args: Array<String>) {

    val screenView = ScreenView()

    screenView.listener = ButtonClickListener("Second")
    screenView.buttonLambda.performClick()
    screenView.buttonReference.performClick()

    val intFunction: (hello: Int) -> Int = IntTransformer()

    intFunction(30)

}